### ISSUE TITLE
Удалить перегрузку

### ISSUE THREAD

**Issue by IvanOsokin** [IvanOsokin/Just_Something#2]
https://github.com/IvanOsokin/Just_Something/blob/1fc44db1b66e973d27f186a20870412831a8b0da/projects/libalienland/src/Bullet.cpp#L10

**Comment by KOMMYHAP** [comment]
Это какой-то случайный issue?

**Comment by IvanOsokin** [comment]
Это просто пометка была. Ну и заодно попробовал, потому что препод с курсов недочеты указывал таким образом. Для чего вообще используется этот Issue?

**Comment by KOMMYHAP** [comment]
Пользователи репозитория, которые не имеют возможность редактировать код, могут заводить issue (вопрос/проблема/баг), чтобы обсудить что-то с участниками репозитория. Часто оформляют в issue баги или запросы на новые фичи, которые в дальнейшем могут перекочевать в pull request, если хватает возможностей самому оформить решение.

**Comment by KOMMYHAP** [comment]
Но сами пул реквесты также могут использоваться в гит флоу самими участниками репозитория. Часто используется подход, когда фичи делаются в отдельных ветках, а в дальнейшем сливаются с основной веткой с помощью мердж реквестов (не уверен, что мердж реквесты и пул реквесты это одно и тоже, тут следует почитать доп. инфу). В дальнейшем я планирую нас на подобный гитфлоу перевести ради хорошей практики.
